name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # FRONTEND
      - name: Install deps (root)
        run: npm install

      - name: Lint
        run: npx biome check .

      - name: Build frontend
        run: npm run build --prefix frontend

      - name: Install backend deps
        run: npm install --prefix backend